# Generated by Django 5.2.17 on 2026-09-23 20:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste', '0002_wastecategory_updated_at_wastereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams')], default='kg', max_length=10)),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='collection_proof/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('waste_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_request', to='waste.wastereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
