# Generated by Django 5.2.17 on 2026-09-24 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='actual_piece_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
