# Generated by Django 5.2.17 on 2026-09-24 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_collectionrequest_actual_piece_count'),
        ('waste', '0005_wastereport_waste_report_piece_estimate_must_be_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('actual_piece_count__isnull', True), ('actual_piece_count__gte', 1), _connector='OR'), name='collection_piece_count_must_be_positive'),
        ),
    ]
