# Generated by Django 5.2.17 on 2026-09-24 08:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('waste', '0003_wastecategory_token_rate_per_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='marketplacematerial',
            options={'ordering': ['-active', 'name']},
        ),
        migrations.RenameField(
            model_name='buyerrequest',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='buyerrequest',
            old_name='requested_material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='buyerrequest',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='buyerrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='material_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_buyer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerrequest',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('ton', 'Tonnes'), ('piece', 'Pieces')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_materials', to='waste.wastecategory'),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='image',
            field=models.ImageField(blank=True, upload_to='marketplace/materials/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='buyerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacematerial',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='marketplacematerial',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('ton', 'Tonnes'), ('piece', 'Pieces')], default='kg', max_length=10),
        ),
        migrations.AddIndex(
            model_name='marketplacematerial',
            index=models.Index(fields=['active', 'category'], name='marketplace_active_8330d0_idx'),
        ),
    ]
