# Generated by Django 5.2.17 on 2026-09-24 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('marketplace', '0003_alter_buyerrequest_email_alter_buyerrequest_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacematerial',
            name='preparation_status',
            field=models.CharField(choices=[('ready', 'Ready for preparation'), ('draft', 'Draft'), ('published', 'Published')], db_index=True, default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_marketplace_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacematerial',
            name='source_collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_material', to='collections.collectionrequest'),
        ),
    ]
