# Generated by Django 5.2.17 on 2026-09-24 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0003_collectionrequest_collection_piece_count_must_be_positive'),
        ('waste', '0005_wastereport_waste_report_piece_estimate_must_be_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('eligibility_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_cashout_min_tokens', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('collector_payout_min_tzs', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('payout_method', models.CharField(default='mobile_money', max_length=20)),
                ('provider_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_payouts', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_collector_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('customer_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('collector_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('operations_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='economic_policies', to='waste.wastecategory')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='material_rate', to='waste.wastecategory')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=10)),
                ('verified_quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('material_rate_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collector_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('operations_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_tokens', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collector_base_earning', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operations_allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_collector_earning', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='economics.collectorbonus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waste.wastecategory')),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='economic_settlement', to='collections.collectionrequest')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economics.economicpolicy')),
                ('material_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economics.materialrate')),
            ],
            options={
                'ordering': ['-settled_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('collection_earning', 'Collection earning'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment'), ('payout', 'Payout'), ('refund', 'Refund')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_transactions', to='collections.collectionrequest')),
                ('collector_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='economics.collectorwallet')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='economics.collectorpayout')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='collector_transaction_amount_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('collection__isnull', False), ('transaction_type', 'collection_earning')), models.Q(('collection__isnull', False), ('transaction_type', 'bonus')), ('transaction_type__in', ['adjustment', 'payout', 'refund']), _connector='OR'), name='collector_transaction_collection_usage_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='economicpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('customer_percent__gte', 0), ('collector_percent__gte', 0), ('operations_percent__gte', 0)), name='economic_policy_percentages_nonnegative'),
        ),
    ]
