# Generated by Django 5.2.17 on 2026-09-23 21:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wastecategory_updated_at_wastereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='token_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
