# Generated by Django 5.2.17 on 2026-09-24 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_wastecategory_token_rate_per_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastecategory',
            old_name='token_rate_per_kg',
            new_name='token_rate',
        ),
        migrations.AddField(
            model_name='wastecategory',
            name='reward_unit',
            field=models.CharField(choices=[('kg', 'Kilogram (KG)'), ('piece', 'Piece')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='estimated_piece_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='estimated_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
