# Generated by Django 5.2.17 on 2026-09-24 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_rename_token_rate_per_kg_wastecategory_token_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wastereport',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_piece_count__isnull', True), ('estimated_piece_count__gte', 1), _connector='OR'), name='waste_report_piece_estimate_must_be_positive'),
        ),
    ]
