# Generated by Django 5.2.17 on 2026-09-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('wallet', '0002_wallet_updated_at_wallettransaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collection__isnull', False), ('transaction_type', 'collection_reward')), models.Q(('collection__isnull', True), ('transaction_type__in', ['reward_redemption', 'cashout', 'adjustment'])), _connector='OR'), name='wallet_transaction_collection_usage_is_valid'),
        ),
    ]
