# Generated by Django 5.2.17 on 2026-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_wallettransaction_wallet_transaction_collection_usage_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='collection_reward_material',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='collection_reward_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='collection_reward_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='collection_reward_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram (KG)'), ('piece', 'Piece')], max_length=10, null=True),
        ),
    ]
